from armas.armas_arqueiro import *
from armas.armas_assassino import *
from armas.armas_barbaro import *
from armas.armas_bardo import *
from armas.armas_cavaleiro import *
from armas.armas_clerigo import *
from armas.armas_druida import *
from armas.armas_engenheiro import *
from armas.armas_feiticeiro import *
from armas.armas_guerreiro import *
from armas.armas_ladino import *
from armas.armas_mago import *
from armas.armas_monje import *
from armas.armas_necromante import *
from armas.armas_paladino import *
